### ISSUE TITLE
embedded thumbnails of pdfs

### ISSUE THREAD

**Issue by peterreimer** [hbz/thumby#1]
some pdf files contain thumbnails of every page used as a preview in the reader software. Using the thumbnail of the first image might be faster, or more accurate or even both.

**Comment by jschnasse** [comment]
Hi Peter,
I installed https://github.com/hbz/thumby/pull/2 on test. Please provide some feedback. 
Jan

**Comment by jschnasse** [comment]
katharina told me, that she is happy with the updated version. I'm not totally sure, if embedded previews will overrule the general thumbnail routine. If you can provide a failing test case, I will reopen this issue.
